### ISSUE TITLE
Not able to retrieve data from fire-base

### ISSUE THREAD

**Issue by karthik1531** [karthik1531/Mind-Game#2]
https://github.com/karthik1531/Mind-Game/blob/83fdd9e6c38ad7a1a10a8f5e6ca8408c2bcf865e/js/firebase-app.js#L2-L33

**Comment by karthik1531** [comment]
This is from last commit.

**Comment by ankushdharkar** [comment]
`Last` may be relative, especially if you commit more things after posting the comment

Anyway, I think we have taken care of this problem today. Closing this issue
